---
title: Tyler Coburn
author: R package build
date: '2021-03-05'
slug: []
categories:
  - art
tags:
  - art
description: ''
keywords: []
stylesheet: post.css
---

Dear Tyler,

**I am a big, big fan of your work!!!**

I include three exclamation points (rather than just one), I use the word, “big” twice, and I use a 12-sized font (to contrast with the 11-sized font in the rest of the letter) in the above encomiastic opening, because a fanmail letter begs for such hyperbolic conventions. And of course, I sincerely, truly do admire your work!!! (note the superfluous use of two adjacent adverbs to infuse the sentence with intensity; if read aloud, the enunciation of “sincerely” and “truly” should be elongated and intonated more deeply). The number of exclamation marks used should also convince you of the sincerity behind my admiration, because these exclamation points were once referred to as “admiration points” by the 14th-century Italian poet, Iacopo Alpoleio da Urbisaglia, who claimed to have invented this highly affable tool.   

In writing you a letter of admiration, I feel it imperative to be utterly transparent with the orthographic and sociolinguistic choices I make in this letter, because much of your work brilliantly makes transparent what is otherwise overlooked, misunderstood, or violently erased; particularly with your projects questioning the autonomy and authority given to certain contemporary forms of technology. In this case, Microsoft Word’s clean and blemish-free aesthetic belies any pimpling of anxiety and popping of indecision associated with writing. Coincidentally (or not?), the word, “encomiastic” which I used above, spells “cosmetician” when the letters are rearranged. But rather than convey admiration in a beautified way, I want to lay bare the unseemly and inconvenient truths within the process of writing. In doing so, I highlight and perform what you invite your audience and students to do – reflect, dig deeper, intimate, question, and hold hands. Why hold hands?? Because I see your work as a beautiful and necessary invitation to personalize everyday experiences that are increasingly becoming sterile and disconnected. Your art are prompts for us to go beyond the veneer of social normativity, technological efficiency, historical narrativization, and legal discourse. 

In closing, after perusing many metaphors that could best encapsulate the impressive intricacy of your work, I settled on the Deleuzian fold. I italicize the Deleuzian fold to highlight the beautifully baroque nature of your thinking: “Italic” comes from the Latin italicus, or "of Italy"; the work of Italian sculptor, Gian Lorenzo Bernini, exquisitely exemplifies the Baroque style; Bernini’s sculpture, David comes from the biblical figure of David who is about to throw the stone that will bring down Goliath; your work highlights seemingly implacable antagonisms between the Goliaths of law, social normativity, bureaucracy, and Siri, and the everyday Davids, including you and I. I see your work (particularly your speech!) to be generative, distinctive, and indicative of depth as well as possibility; just as the Deleuzian folds. You invite your audience into an ever-unfolding conversation between the material, embodied and transcendent. 

Thank you for offering such alluring labyrinths for our senses to meander through, rapaciously explore, and weave into new, thoughtful forms. 

With respect and gratitude,

Aidyn Mills
