---
title: Spyros Simotas
author: Aidyn Mills
date: '2020-05-08'
slug: spyros-simotas
categories:
  - fan-mail
tags:
  - friendship
  - life
  - art
  - project
description: ''
keywords: []
stylesheet: post.css
---

Dear Spyros,


I am so grateful to have this opportunity to properly tell you how much I admire your artistic practice. It’s perfect that our art piece/research project, that deconstructs lines between what we call “life” and “art,” has provoked this letter. For you have mastered the dissolution of any such lines; and in such admirably artful, humble and inspiring ways.

As I’ve thought about these fan mail letters that we’re writing, I started by imagining personalities who are so different from me, that I’ve placed them in some imagined place “above” the reality in which I live. As if planes of artistry and creativity are measured in terms of height, with the most amazing artists living in the heavens, and the least talented on the mundane, ground level. Yet, pinnacles and loftiness don’t seem to capture the kind of “art” I find inspiring. As I get older, I’m truly impressed by those who integrate life “on-the-ground” with “art”; those who can move in and out of everyday spaces without much flair, pomp and circumstance, and reliance on the label “artist”, yet live the mundane so magnificently; and those who live and embody the concepts we spend too much time talking about and admiring from a distance. 

In my opinion, that is you. In the 8 years (?!) I’ve known you, I have grown to admire how you see. You see the world different from most, such that you don’t have to manipulate what you see with excessive color, media, or arrangement; you let life be as it is. And you capture it. As we both get older, we’re discovering that life already is beautiful. But it takes wisdom, humility, and care to recognize its beauty; and to share it. We have to pause, take the time to listen and look, and we will see, hear, and know “art” in the life around us… car washes, buildings, a glance, a glass… it all is beautiful. Perhaps it’s like the French cooks – they don’t add too much to make a delicious meal; they let the ingredients speak for themselves. Imagine if we signed our paintings and photographs, “by: the plant in this picture.” 

Thank you, dear friend for living as you do – slowly, thoughtfully, mindfully, humbly, under-the-radar, unconventionally, respectfully, with humor, creatively, sweetly. You haven’t separated yourself from others on any zenith. Yet, you’ve inspired me deeply. Thank you for being you; thank you for sharing what you do; thank you for collaborating with me; and thank you for seeing the beauty in me, so I don’t have to rearrange myself in any way.


Yours truly,

Lorraine
