---
title: Jason Hendrik Hansma
author: Aidyn Mills
date: '2021-03-21'
slug: []
categories:
  - art
tags:
  - art
  - http://www.jasonhendrikhansma.com/
description: ''
keywords: []
---

Dear Jason,

What a pleasure it was talking with you! I was especially delighted to learn that your practice is synonymous with your way of being. Your work explores the liminal: the steps before standardization, thoughts between coherence, the tedium beyond the glamour, and the textures, voices and rhythms lost to master narratives and structures. Archives, waves, clubs, and breezes do indeed merit our attention. With your art, we realize that. With our conversation, I realized that.

And our conversation was entirely liminal and refreshingly ambiguous! Led by your incessant questions and spontaneous observations. It was a thrill to volley thoughts and suggestions back and forth with no desire to keep score. Who knew where we would arrive nor what our egos thought?? I just felt energized and inspired during and after. Maya Angelou's quote comes to mind here: “I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.” This falls in line with your work at your curatorial studio, Shimmer. I'm curious what the effervescence from our conversation, with all its insightful glimmer and enlivening shimmer, will provoke in the coming moments, weeks, steps, and folds.

I'm grateful for our conversation as a vivid reminder to live and practice in process. It does make me wonder, to what extent concepts, such as “process,” deliberately drive your work / daily living / the styling of your individual moments. I can characterize our virtual encounter in Deluezian terms, as a becoming, as if to further validate our meeting. Yet as Georges Bataille wrote, I would simply be giving a “frock coat to what is.” I suppose I would prefer that you just imagine me winking at you the whole time as I'm writing this letter. You are most certainly in on the joke at which we often forget to laugh. For, all these words are as formless and formidable as _haute couture_ and my morning ginger tea.

Sincerely, 

Aidyn