---
title: Alejandra Pizarnik
author: Aidyn Mills
date: '2020-06-29'
slug: alejandra-pizarnik
categories:
  - fan-mail
tags:
  - poetry
  - writing
  - language
description: ''
keywords: []
stylesheet: post.css
---

Dear Alejandra,

I write to say thank you for your naked appraisal of life. I sometimes loathe all the lace and lipstick with which we cover what we see and do; which I myself have done, and on occasion still do. 

You reckoned with the limitations of words, using words themselves. You faced fears with mirrors. You wrote in the darkness to find light. So it is in your words, I find myself. I find myself in your search for a face without fear; in a girl elusively self-portraited; in a palimpsestic ambition for what should be, yet a compassionate nod towards what was; in self-imposed censures; and as a migrant soul beholden to the irrelevance of words. 

I am grateful for your honesty, and am saddened by your death. Yet, your shadows, which you invited into your poetry, become our shadows. Through your words, we see our own shadows more clearly. With words, the act of naming is both treacherous and liberating. 

Below I respond to your poem, “Continuity.” And so our words commiserate and collaborate. And in my response, I find freedom. 

> Not naming things by their names. Things have barbed edges, lush vegetation. But who is speaking in this room full of eyes? Who gnaws with a mouth made of paper? Names that come up, shadows with masks. Cure me of this void, I said. (The light loved itself in this darkness of mine. I knew that there was absence when I found myself saying, It is I.) Cure me, I said. --- “Continuity” Alejandra Pizarnik, 1963


> I too was once pricked by the rigidity of things, these barbed edges and insistent spokes. Then I noticed the light catching on the contours of these metal rims, revealing speckles of my reflection. I began to turn these and other things at just the right angles, and soon they all became the same things. And I, too, knew there was emptiness when I saw myself. --- “Emptiness” Aidyn Mills, 2020


With deep respect,

Aidyn

- - - 

<small>Alejandra Pizarnik was an Argentine poet who wrote significantly about silence, the limitations of language, solitude, and the body.</small>

