---
title: Gordon Hall
author: Aidyn Mills
date: '2020-07-27'
slug: gordon-hall
categories:
  - art
  - contemporary
  - fan-mail
tags: []
description: ''
keywords: []
---


Dear Gordon,  

I just came across your piece, The Number of Inches Between Them. What a treasure.

What first caught my attention was the similarity between your work and ours of writing letters of
appreciation to artists. But after a few minutes of listening to you read your letter of gratitude to
your respective artist, I realized there was more to your work. I came to a simple, yet profound
realization about something I’ve been contemplating: whether to know someone or something
requires

a  
depth  
of knowledge:  
the more  
we know  
the more  
we understand?  

Yet, watching as you interacted with a simple, white bench, “a beautiful and strange” bench, the
phrase, longitudinal engagement, came to mind. A thoughtful and meaningful extension of

a       t      t      e      n      t      i       o       n

to what is there. I realized that a simple gesture, movement, articulation or look can be extended
to provoke an utterly sweet and powerful feeling of knowing. Yet, prolonged attention is unusual
or misunderstood in the ways we tend to move and in the spaces we circulate. We often
entertain rather than attend; economize rather than engage. We dare not pair a persistence of
time with experience, let alone an experience as simple as a glance, silence, or a tender touch.

But. what. if. we. did?

While I’m grateful for such a beautiful and compelling public performance, I’ve realized that this
one performance is most probably a single evocation of countless singular private moments in
which you’ve offered your “slow and quiet” attention to others, both human and inanimate. In the
brief time I’ve known you, it is clear that your philosophies are your practice. You exude a quiet
yet powerful presence that compels others to similarly pause. And attend. Have you always
been this thoughtful? What provoked you to focus your practice in this way?

Many sincere thanks for your example. I too want to feel every length and angle of simple
moments.

Yours truly,  
Aidyn
