---
title: Barbara Rubin
author: Aidyn Mills
date: '2020-06-12'
slug: barbara-rubin
categories:
  - fan-mail
tags:
  - experimental
  - film
  - 60s
description: ''
keywords: []
stylesheet: post.css
---

Dear Barbara,

I wish I was alive with you in the 60s. I crave the boldness and zest that you lived with; to immerse myself in it, to contortion my body and mind with it, to create with it. In many ways I see myself in you: the childlike curiosity; a laser-sharp focus on what you want, free of the burden of external opinions of a myopic mainstream; and a gloriously transcendent vision of life, yet an effortless capacity to connect with other beautiful humans. I imagine if we were alive together today, we would converse about the archaism of feminism and the absolute necessity of sex; explore ourselves and others with artful urgency; and avidly kiss in front of your camera.

As I write this letter, I ask myself, why haven’t I pushed myself as much as you have? The need and hunger are certainly there, yet why haven’t I paired passion with action? Yes, you had the advantage of life in New York City in the 60s before “surrealism” became an academic concept. But was that really an advantage? Does an artist need an enclave of endlessly effervescent élan in which to create, think, and be more than what our comfort zones allow? Am I already immersed in my own enclave of creativity? Is exceptional circumstance nothing more than our own creation? 

Writing this letter to you, I seem to have answered my own questions. I realize, I am already creating. I am already creating my own Christmas on Earth.



With deep respect,

Aidyn
