---
title: L.M.
author: Aidyn Mills
date: '2020-04-28'
slug: lydia-moyer
categories:
  - fan-mail
tags:
  - woman
  - art
  - experimental
  - uva
description: ''
keywords: []
stylesheet: post.css
---

Dear L.M,

I’m taking this opportunity to (semi-formally) offer you words of gratitude and admiration for your work as an artist. It is a bit strange that I’m directing a fan letter to you, a close friend, but my curiosity of what I would say, and what you would say, overrode any reservations on my part. I do hope you read this letter with the sincerity with which it is intended. Although a recipient of this fan mail and, therefore, part of a larger research project and artistic process, there is nothing contrived in my words; you are truly held in the highest of esteems! 

First off, I want to confess and express remorse for only having truly explored your artwork two months ago after knowing you for 2 years as a friend! Perhaps my late discovery of your art signifies your humility?? That is, when we get together, you don’t speak about your work as an artist; nothing about its emotional, technical, political, and/or creative aspects. So I often forget that you are, in fact, an artist! Because I do know you as a friend, I would attribute your lack of conversation on the topic of “art” to a certain (admirable) ability (and/or need?) to detach from the identity of an “artist.” I’m curious about this. I also know that your work, which has been presented and very well-received in the institutional and disciplinary world of “art,” defies disciplinary boundaries and eschews conventional classifications. So perhaps your reticence on the topic of “art” is consistent with the nature of your work? Would indulging your identity as a (successful) artist through conversation, contradict art that does not depend on rational and discursive explorations?

I appreciate you indulging my curiosities about how you inhabit the life of “the artist.” While I openly work through my queries in this letter about you personally, and other artists whose work I admire, ultimately I am expressing deep respect for not only the bold and provocative work you create, but also the way in which you have gracefully maintained such a strong and fascinating presence, without having to resort to an identity as an artist. So what then does it mean to be an “artist”?!


Yours Truly,


Aidyn  
