---
title: "Erica Baum"
author: "Spyros Simotas"
date: '2021-01-19'
output: word_document
categories:
- art
- contemporary
- photography
- concrete poetry
tags:
- photography
- visual poetry
- concrete poetry
- print
- book
description: ''
keywords: []
slug: erica-baum
---

Dear Erica, 

I recently watched a video presentation of your book _The Naked Eye_ by Simon Morris [on vimeo](https://vimeo.com/464151163). As the progress bar keeps filling up and Simon Morris flips through your book explaining your brilliant idea, I am trying to remember when and where I've seen your work before. In a new tab, I type your name. 

On YouTube, the first [video](https://www.youtube.com/watch?v=Ty-C3Lyp4tg&ab_channel=ApertureFoundation) on top of the list is from a talk you gave at Aperture Foundation in 2018. You walk your audience through your projects chronologically. Each one of your projects branches organically off from your fascination with the material world of texts, and the places where they live: libraries, books... Or die: blackboards and library card catalogs. You have found an abundant source of inspiration in print and its contextual surroundings. 

There is barely any gear talk around your pictures. In the portraits that surfaced during my search there is none in which you carry a camera. We see you with books, we see you reading. In [an interview](https://bombmagazine.org/articles/erica-baum-1/) you say that your work is an "homage to the love of reading." And yet, your images are nowhere near the [19th century trope of portraits of readers](https://www.google.com/search?q=19th+century+portraits+of+readers&source=lnms&tbm=isch&sa=X&ved=2ahUKEwil493v6PjuAhVjD1kFHaK6D1gQ_AUoAXoECA8QAw&biw=1248&bih=778) immersed in their reading. Your work takes us closer to see the materiality of the book. It brings awareness to the ways in which we manipulate books before or after we are through reading, or those exquisite moments when the attention veers off the text to focus on texture, microscopic details, or follow the impromptu dance performance of a ray of light on the page.      

Back to the Aperture Foundation video. As you explain the origin story behind your projects, you naturally take us to Jersey City and the closed catalog drawer that reads _Jersey City-Jesus._ The next slide comes with four seconds of silence. The drawer is now open, and in it, a sea of cards stacked against each. One of them stands out like a sail boat on a sunny day. It reads _Reality_.     

What is there to say, really? I love your work. 

With admiration,   
Spyros 





